
---

var:
  leader-elector-git-repo-config: &leader-elector-git-repo-config
    uri: https://github.com/instana/leader-elector.git
    username: ((instanacd-github-api-token))
    password: x-oauth-basic
    branch: ((branch))
    git_config:
      - name: user.name
        value: Stan
      - name: user.email
        value: stan@instana.com

resource_types:

  - name: slack-notification
    type: registry-image
    source:
      repository: cfcommunity/slack-notification-resource
      tag: latest

  - name: codebuild
    type: registry-image
    source:
      repository: cedricziel/concourse-codebuild-resource
      tag: "0.1.14"

  - name: docker-manifest
    type: registry-image
    source:
      repository: gcr.io/instana-agent-qa/concourse-docker-manifest-resource
      username: _json_key
      password: ((project-berlin-tests-gcp-instana-qa))

resources:

  - name: pipeline-source
    type: git
    icon: github
    source:
      <<: *leader-elector-git-repo-config
      paths:
      - ci/

  - name: leader-elector-repository
    type: git
    icon: github
    source:
      <<: *leader-elector-git-repo-config

  - name: leader-elector-version
    type: semver
    icon: alpha
    source:
      <<: *leader-elector-git-repo-config
      driver: git
      file: NEXT_VERSION
      commit_message: Bump the NEXT leader-elector version to %version%

  - name: build-bundle
    type: s3
    icon: zip-disk
    source:
      bucket: instana-agent-leader-elector-codebuild
      versioned_file: context.zip
      access_key_id: ((codebuild-key.key_id))
      secret_access_key: ((codebuild-key.key_secret))
      region_name: us-west-2
      skip_download: true

  - name: codebuild-containers
    type: codebuild
    icon: aws
    source:
      project: instana-leader-elector-codebuild
      region: us-west-2
      access_key_id: ((codebuild-key.key_id))
      secret_access_key: ((codebuild-key.key_secret))

  - name: leader-elector-image-amd64
    type: registry-image
    icon: docker
    source:
      repository: gcr.io/instana-agent-qa/leader-elector
      tag: latest-amd64
      username: _json_key
      password: ((project-berlin-tests-gcp-instana-qa))
  - name: leader-elector-image-arm64
    type: registry-image
    icon: docker
    source:
      repository: gcr.io/instana-agent-qa/leader-elector
      tag: latest-arm64
      username: _json_key
      password: ((project-berlin-tests-gcp-instana-qa))
  - name: leader-elector-image-s390x
    type: registry-image
    icon: docker
    source:
      repository: gcr.io/instana-agent-qa/leader-elector
      tag: latest-s390x
      username: _json_key
      password: ((project-berlin-tests-gcp-instana-qa))
  - name: leader-elector-image-ppc64le
    type: registry-image
    icon: docker
    source:
      repository: gcr.io/instana-agent-qa/leader-elector
      tag: latest-ppc64le
      username: _json_key
      password: ((project-berlin-tests-gcp-instana-qa))

  - name: slack-alert-team-agent
    type: slack-notification
    source:
      url: ((slack-webhook-team-agent.webhoook_url))

# containers.instana.io ##############
  - name: leader-elector-instana
    type: registry-image
    icon: docker
    source: &containers-instana-io
      repository: containers.instana.io/instana/release/agent/leader-elector
      username: ((containers-instana-io-creds.username))
      password: ((containers-instana-io-creds.password))

  - name: manifest-instana
    type: docker-manifest
    icon: docker
    source: *containers-instana-io

# icr.io ##############
  - name: leader-elector-icr
    type: registry-image
    icon: docker
    source: &icr-io
      repository: icr.io/instana/leader-elector
      username: iamapikey
      password: ((concourse-icr-containers-public.password))

  - name: manifest-icr
    type: docker-manifest
    icon: docker
    source: *icr-io

############
### Jobs ###
jobs:
  - name: self-update
    max_in_flight: 1
    plan:
      - get: pipeline-source
        trigger: true
      - set_pipeline: self
        file: pipeline-source/ci/pipeline.yml
        vars:
          branch: ((branch))

  - name: prepare-build-bundle
    max_in_flight: 1
    plan:
      - get: leader-elector-repository
      - task: package-build-bundle
        config:
          platform: linux
          image_resource:
            type: registry-image
            source:
              repository: ubuntu
              tag: focal
          inputs:
            - name: leader-elector-repository
              path: .
          run:
            path: bash
            args:
              - -ce
              - |
                date
                apt update
                apt install -yqq zip unzip tar
                zip -r target/context.zip .
          outputs:
            - name: target
      - put: build-bundle
        params:
          file: target/context.zip

  - name: multiarch-leader-elector-images-build
    max_in_flight: 1
    plan:
      - get: build-bundle
        trigger: true
        passed: [ prepare-build-bundle ]
      - get: leader-elector-repository
      - get: leader-elector-version

      - load_var: new_leader_elector_version
        file: leader-elector-version/number
        reveal: true
      - load_var: commit-sha
        file: leader-elector-repository/.git/HEAD
        reveal: true
      - load_var: s3-artifact-version
        file: build-bundle/version
        reveal: true

      # spin off AWS CloudBuild jobs to build operator
      # images for the different target platforms:
      - in_parallel:
          fail_fast: true
          steps:
            - put: codebuild-containers
              params:
                source_version: ((.:s3-artifact-version))
                env_var_overrides:
                  ELECTOR_VERSION: ((.:new_leader_elector_version))
                  COMMIT_SHA: ((.:commit-sha))
      # upload the AWS CloudBuild built images to GCR:
      - in_parallel:
          fail_fast: true
          steps:
            - put: leader-elector-image-amd64
              params:
                  image: codebuild-containers/artifacts/amd64-image.tar
                  additional_tags: codebuild-containers/artifacts/amd64-tag
            - put: leader-elector-image-arm64
              params:
                  image: codebuild-containers/artifacts/arm64-image.tar
                  additional_tags: codebuild-containers/artifacts/arm64-tag
            - put: leader-elector-image-s390x
              params:
                  image: codebuild-containers/artifacts/s390x-image.tar
                  additional_tags: codebuild-containers/artifacts/s390x-tag
            - put: leader-elector-image-ppc64le
              params:
                  image: codebuild-containers/artifacts/ppc64le-image.tar
                  additional_tags: codebuild-containers/artifacts/ppc64le-tag

  - name: multiarch-leader-elector-manifest-publish
    max_in_flight: 1
    plan:
      - get: leader-elector-repository
        trigger: true
        passed: [ multiarch-leader-elector-images-build ]

      - in_parallel:
        - get: leader-elector-image-amd64
          params:
            format: oci
          passed: [ multiarch-leader-elector-images-build ]
        - get: leader-elector-image-arm64
          params:
            format: oci
          passed: [ multiarch-leader-elector-images-build ]
        - get: leader-elector-image-s390x
          params:
            format: oci
          passed: [ multiarch-leader-elector-images-build ]
        - get: leader-elector-image-ppc64le
          params:
            format: oci
          passed: [ multiarch-leader-elector-images-build ]

      - get: leader-elector-version
      - load_var: new_leader_elector_version
        file: leader-elector-version/number
        reveal: true

      - task: multiarch-tags
        privileged: true
        file: leader-elector-repository/ci/create-tag-file.yml
        output_mapping:
          version: version
        vars:
          version: ((.:new_leader_elector_version))

# containers.instana.io ##############
      - in_parallel:
        - put: leader-elector-instana
          params:
            image: leader-elector-image-amd64/image.tar
            additional_tags: version/tag-amd64
        - put: leader-elector-instana
          params:
            image: leader-elector-image-arm64/image.tar
            additional_tags: version/tag-arm64
        - put: leader-elector-instana
          params:
            image: leader-elector-image-s390x/image.tar
            additional_tags: version/tag-s390x
        - put: leader-elector-instana
          params:
            image: leader-elector-image-ppc64le/image.tar
            additional_tags: version/tag-ppc64le

      - put: manifest-instana
        params:
          tag_file: leader-elector-version/number
          manifests:
            - arch: amd64
              os: linux
              digest_file: leader-elector-image-amd64/digest
            - arch: arm64
              os: linux
              digest_file: leader-elector-image-arm64/digest
            - arch: s390x
              os: linux
              digest_file: leader-elector-image-s390x/digest
            - arch: ppc64le
              os: linux
              digest_file: leader-elector-image-ppc64le/digest

# icr.io ##############
      - in_parallel:
        - put: leader-elector-icr
          params:
            image: leader-elector-image-amd64/image.tar
            additional_tags: version/tag-amd64
        - put: leader-elector-icr
          params:
            image: leader-elector-image-arm64/image.tar
            additional_tags: version/tag-arm64
        - put: leader-elector-icr
          params:
            image: leader-elector-image-s390x/image.tar
            additional_tags: version/tag-s390x
        - put: leader-elector-icr
          params:
            image: leader-elector-image-ppc64le/image.tar
            additional_tags: version/tag-ppc64le

      - put: manifest-icr
        params:
          tag_file: leader-elector-version/number
          manifests:
            - arch: amd64
              os: linux
              digest_file: leader-elector-image-amd64/digest
            - arch: arm64
              os: linux
              digest_file: leader-elector-image-arm64/digest
            - arch: s390x
              os: linux
              digest_file: leader-elector-image-s390x/digest
            - arch: ppc64le
              os: linux
              digest_file: leader-elector-image-ppc64le/digest

      - put: leader-elector-repository
        params:
          repository: leader-elector-repository
          tag: leader-elector-repository/NEXT_VERSION
          only_tag: true
      - put: leader-elector-version
        params: {bump: patch}
      - put: slack-alert-team-agent
        params:
          channel: tech-agent-delivery-notifications
          text: New version of the Leader Elector image; ((.:new_leader_elector_version)) released!

